version: 2.1
orbs:
  docker: circleci/docker@1.4.0
jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: mohtar/hello-world
          tag: $CIRCLE_BRANCH-$CIRCLE_SHA1
      - docker/push:
          image: mohtar/hello-world
          tag: $CIRCLE_BRANCH-$CIRCLE_SHA1
workflows:
  build-and-push:
    jobs:
      - build-and-push
